universe = vanilla
Executable = condor_executable.sh
Arguments = $(Process)
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Transfer_Input_Files = zcfiles.tgz
Output = zcntupler_$(Cluster)_$(Process).stdout
Error = zcntupler_$(Cluster)_$(Process).stderr
Log = zcntupler_$(Cluster)_$(Process).log
notify_user = ${LOGNAME}@FNAL.GOV
+LENGTH="SHORT"
x509userproxy = /tmp/x509up_u42382
Queue 2 
