universe = vanilla
Executable = condor_executable.sh
Arguments = $(Process)
Should_Transfer_Files = YES
WhenToTransferOutput = ON_EXIT
Transfer_Input_Files = ../NtupleProcessor.exe,../zcAnalysisConfig_runII.ini,../zcNPC_runII.ini,dsList.txt,../NtupleProcessor/etc/zcControlPlotConfig_default.ini
Output = zcntupler_$(Cluster)_$(Process).stdout
Error = zcntupler_$(Cluster)_$(Process).stderr
Log = zcntupler_$(Cluster)_$(Process).log
notify_user = ${LOGNAME}@FNAL.GOV
+LENGTH="SHORT"
x509userproxy = /tmp/x509up_u42382
Queue 44
